version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003:2003"

  eureka-server:
    build: platform-service/discovery
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.instance.prefer-ip-address: true
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  one:
    build: business-service/one
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      server.port: 8081
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  two:
    build: business-service/two
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      server.port: 8082
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  common:
    build: business-service/common
    ports:
      - "8077:8077"
    depends_on:
      - eureka-server
    environment:
      server.port: 8077
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  two-api:
    build: business-service/two-api
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      server.port: 8083
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/

  apigateway:
    build: platform-service/apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - one
      - two
    environment:
      server.port: 8080
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
