zuul:
  routes:
    epam:
      path: /epam/**
      url: https://epam.ua/
    two:
      path: /test/**
      url: http://localhost:8082/redirect
spring:
  application:
    name: apigateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true